[tool.poetry]
name = "01-screenshot"
version = "0.1.0"
description = ""
authors = ["Hylson <hvescovi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyscreenshot = "^3.1"
pillow = "^12.1.1"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
