[tool.poetry]
name = "04-with-ia-filmes-302"
version = "0.1.0"
description = ""
authors = ["Hylson <hvescovi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.3"
flask-cors = "^6.0.2"
pony = "^0.7.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
